    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="home/vendors/@popperjs/popper.min.js"></script>
    <script src="home/vendors/bootstrap/bootstrap.min.js"></script>
    <script src="home/vendors/is/is.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="home/vendors/fontawesome/all.min.js"></script>
    <script src="home/assets/js/theme.js"></script>